/***************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are copyright (C) 2010, Sensia Software LLC
 All Rights Reserved.

 Contributor(s): 
    Alexandre Robin <alex.robin@sensiasoftware.com>
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.api.service;

import org.sensorhub.api.common.Event;


/**
 * <p><b>Title:</b>
 * ServiceEvent
 * </p>
 *
 * <p><b>Description:</b><br/>
 * Simple base data structure for all events generated by services
 * </p>
 *
 * <p>Copyright (c) 2010</p>
 * @author Alexandre Robin
 * @date Nov 5, 2010
 */
public class ServiceEvent extends Event
{
    private static final long serialVersionUID = -8061369033080200650L;
    
    
    /**
     * Possible service event types
     */
    enum EventType
    {
        ENABLED,
        DISABLED,
        COMMAND_AVAILABLE,
        NEW_DATA_AVAILABLE
    };
    
    
    /**
     * ID of service that generated the event
     */
    protected String serviceId;
    
    
    /**
     * Type of service event
     */
    protected EventType type;
    
    
    /**
     * Sole constructor
     * @param serviceId Id of originating service
     * @param type type of event
     */
    public ServiceEvent(String serviceId, EventType type)
    {
        this.serviceId = serviceId;
        this.type = type;
    }
}
