/***************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are copyright (C) 2010, Sensia Software LLC
 All Rights Reserved.

 Contributor(s): 
    Alexandre Robin <alex.robin@sensiasoftware.com>
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.api.service;

import org.sensorhub.api.common.SensorHubException;


/**
 * <p><b>Title:</b>
 * ServiceException
 * </p>
 *
 * <p><b>Description:</b><br/>
 * Exceptions generated by the service API
 * </p>
 *
 * <p>Copyright (c) 2010</p>
 * @author Alexandre Robin
 * @date Nov 5, 2010
 */
public class ServiceException extends SensorHubException
{
    private static final long serialVersionUID = 2830272527685987575L;
    
    
    public ServiceException(String message)
    {
        super(message);
    }
    
    
    public ServiceException(String message, Throwable cause)
    {
        super(message, cause);
    }
    
    
    public ServiceException(String message, int code, Throwable cause)
    {
        super(message, code, cause);
    }
}
