/***************************** BEGIN LICENSE BLOCK ***************************

The contents of this file are subject to the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one
at http://mozilla.org/MPL/2.0/.

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
for the specific language governing rights and limitations under the License.
 
The Initial Developer is Sensia Software LLC. Portions created by the Initial
Developer are Copyright (C) 2014 the Initial Developer. All Rights Reserved.
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.api.service;

import org.sensorhub.api.common.Event;


/**
 * <p>
 * Simple base data structure for all events generated by services
 * </p>
 *
 * <p>Copyright (c) 2010</p>
 * @author Alexandre Robin
 * @since Nov 5, 2010
 */
public class ServiceEvent extends Event
{
    private static final long serialVersionUID = -8061369033080200650L;
    
    
    /**
     * Possible service event types
     */
    enum EventType
    {
        ENABLED,
        DISABLED,
        COMMAND_AVAILABLE,
        NEW_DATA_AVAILABLE
    };
    
    
    /**
     * ID of service that generated the event
     */
    protected String serviceId;
    
    
    /**
     * Type of service event
     */
    protected EventType type;
    
    
    /**
     * Sole constructor
     * @param serviceId Id of originating service
     * @param type type of event
     */
    public ServiceEvent(String serviceId, EventType type)
    {
        this.serviceId = serviceId;
        this.type = type;
    }
}
