/***************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are Copyright (C) 2013 Sensia Software LLC.
 All Rights Reserved.
 
 Contributor(s): 
    Alexandre Robin <alex.robin@sensiasoftware.com>
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.impl.service.sps;

import org.sensorhub.api.common.SensorHubException;
import org.sensorhub.api.module.IModuleStateLoader;
import org.sensorhub.api.module.IModuleStateSaver;
import org.sensorhub.api.service.IServiceInterface;


/**
 * <p><b>Title:</b>
 * SPSService
 * </p>
 *
 * <p><b>Description:</b><br/>
 * OGC Sensor Planning Service implementation.
 * The service can manage any of the sensors installed on the SensorHub instance
 * and is configured automatically from the information generated by the sensors
 * interface.
 * </p>
 *
 * <p>Copyright (c) 2013</p>
 * @author Alexandre Robin <alex.robin@sensiasoftware.com>
 * @date Sep 6, 2013
 */
public class SPSService implements IServiceInterface<SPSServiceConfig>
{
    SPSServiceConfig config;
    
    
    public SPSService()
    {
        
    }
    
    
    @Override
    public void init(SPSServiceConfig config) throws SensorHubException
    {
        // TODO Auto-generated method stub

    }


    @Override
    public void updateConfig(SPSServiceConfig config) throws SensorHubException
    {
        // TODO Auto-generated method stub

    }


    @Override
    public SPSServiceConfig getConfiguration()
    {
        // TODO Auto-generated method stub
        return null;
    }


    @Override
    public String getName()
    {
        return config.name;
    }
    
    
    @Override
    public String getLocalID()
    {
        return config.id;
    }


    @Override
    public void saveState(IModuleStateSaver saver) throws SensorHubException
    {
        // TODO Auto-generated method stub

    }


    @Override
    public void loadState(IModuleStateLoader loader) throws SensorHubException
    {
        // TODO Auto-generated method stub

    }


    @Override
    public void cleanup() throws SensorHubException
    {
        // TODO Auto-generated method stub
        
    }

}
