/***************************** BEGIN LICENSE BLOCK ***************************

The contents of this file are subject to the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one
at http://mozilla.org/MPL/2.0/.

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
for the specific language governing rights and limitations under the License.
 
The Initial Developer is Sensia Software LLC. Portions created by the Initial
Developer are Copyright (C) 2014 the Initial Developer. All Rights Reserved.
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.api.persistence;

import java.util.List;


/**
 * <p>
 * Tagging interface for basic key/datablock storage implementations
 * </p>
 *
 * <p>Copyright (c) 2010</p>
 * @author Alexandre Robin
 * @since Nov 15, 2010
 */
public interface IBasicStorage<ConfigType extends StorageConfig> extends IDataStorage<DataKey, IDataFilter, ConfigType>
{
    
    /**
     * Retrieves IDs of producers for which data is contained in this storage
     * @return
     */
    public List<String> getProducerIDs();
    
    
    /**
     * Get time range of all data contained in this storage
     * @return
     */
    public long[] getDataTimeRange();
    
    
    /**
     * Get time range of data contained in this storage and generated by the given producer
     * @param producerID
     * @return
     */
    public long[] getTimeRangeForProducer(String producerID);
}
