/***************************** BEGIN LICENSE BLOCK ***************************

The contents of this file are subject to the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one
at http://mozilla.org/MPL/2.0/.

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
for the specific language governing rights and limitations under the License.
 
Copyright (C) 2012-2015 Sensia Software LLC. All Rights Reserved.
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.api.persistence;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import org.sensorhub.api.module.IModule;


public interface IStorageModule<ConfigType extends StorageConfig> extends IModule<ConfigType>
{


    /**
     * Backups storage to specified output stream
     * @param os
     * @throws IOException 
     */
    public void backup(OutputStream os) throws IOException;


    /**
     * Restores storage from backup obtained from specified input stream
     * @param is
     * @throws IOException 
     */
    public void restore(InputStream is) throws IOException;


    /**
     * Commits all changes generated by transactional methods since the last commit event
     */
    public void commit();


    /**
     * Cancels all changes generated by transactional methods since the last commit event
     */
    public void rollback();
    
    
    /**
     * Synchronizes storage with another storage of the same type (potentially remote)
     * @param storage
     * @throws StorageException 
     */
    public void sync(IStorageModule<?> storage) throws StorageException;

}