/***************************** BEGIN LICENSE BLOCK ***************************

The contents of this file are subject to the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one
at http://mozilla.org/MPL/2.0/.

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
for the specific language governing rights and limitations under the License.
 
The Initial Developer is Sensia Software LLC. Portions created by the Initial
Developer are Copyright (C) 2014 the Initial Developer. All Rights Reserved.
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.api.persistence;

import org.sensorhub.api.common.Event;


/**
 * <p>
 * Base class for events generated by storage modules
 * </p>
 *
 * <p>Copyright (c) 2010</p>
 * @author Alexandre Robin
 * @since Nov 12, 2010
 */
public class StorageEvent extends Event
{
    private static final long serialVersionUID = 4070048416493934591L;

    
    /**
     * Possible event types for a StorageEvent
     */
    public enum Type
    {
        STORE,
        UPDATE,
        DELETE,
        GET
    };
    
    
    /**
     * ID of storage that generated the event
     */
    protected String storageId;
    
    
    /**
     * Type of storage event
     */
    protected Type type;  


    public StorageEvent(long timeStamp, String storageId, Type type)
    {
        this.timeStamp = timeStamp;
        this.storageId = storageId;
        this.type = type;
    }
    
    
    public String getStorageId()
    {
        return storageId;
    }


    public void setStorageId(String storageId)
    {
        this.storageId = storageId;
    }


    public Type getType()
    {
        return type;
    }


    public void setType(Type type)
    {
        this.type = type;
    }

}
