/***************************** BEGIN LICENSE BLOCK ***************************

The contents of this file are subject to the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one
at http://mozilla.org/MPL/2.0/.

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
for the specific language governing rights and limitations under the License.
 
Copyright (C) 2012-2015 Sensia Software LLC. All Rights Reserved.
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.api.sensor;

import org.sensorhub.api.common.Event;


/**
 * <p>
 * Simple base data structure for all events generated by sensors (or their drivers)
 * </p>
 *
 * @author Alex Robin <alex.robin@sensiasoftware.com>
 * @since Nov 5, 2010
 */
public class SensorEvent extends Event
{
	/**
	 * Possible event types for a SensorEvent
	 */
    public enum Type
	{
		CONNECTED,
		DISCONNECTED,
		COMMAND_STATUS,
		SENSOR_CHANGED
	};
	
	
	/**
	 * ID of sensor that generated the event
	 */
	protected String sensorId;
	
	
	/**
	 * Type of sensor event
	 */
	protected Type type;
	
	
	/**
	 * Sole constructor
	 * @param timeStamp unix time of event generation
	 * @param source sensor module that generated the event
	 * @param type type of event
	 */
	public SensorEvent(long timeStamp, ISensorModule<?> source, Type type)
	{
	    this.timeStamp = timeStamp;
	    this.source = source;
	    this.sensorId = source.getLocalID();
        this.type = type;
	}
	
	
	@Override
    public ISensorModule<?>  getSource()
    {
        return (ISensorModule<?>)this.source;
    }


    public String getSensorId()
    {
        return sensorId;
    }


    public Type getType()
    {
        return type;
    }
}
