package org.sensorhub.api.sensor;

import org.sensorhub.api.common.Event;


/**
 * <p><b>Title:</b>
 * SensorEvent
 * </p>
 *
 * <p><b>Description:</b><br/>
 * Simple base data structure for all events generated by sensors (or their drivers)
 * </p>
 *
 * <p>Copyright (c) 2010</p>
 * @author Alexandre Robin
 * @date Nov 5, 2010
 */
public class SensorEvent extends Event
{
	private static final long serialVersionUID = -1273002175078885567L;

	
	/**
	 * Possible event types for a SensorEvent
	 */
    public enum Type
	{
		ACTIVATED,
		DEACTIVATED,
		CONNECTED,
		DISCONNECTED,
		NEW_DATA_AVAILABLE,
		COMMAND_STATUS,
		SENSOR_CHANGED
	};
	
	
	/**
	 * ID of sensor that generated the event
	 */
	protected String sensorId;
	
	
	/**
	 * Type of sensor event
	 */
	protected Type type;
	
	
	/**
	 * Sole constructor
	 * @param sensorId ID of originating sensor
	 * @param type type of event
	 */
	public SensorEvent(String sensorId, Type type)
	{
	    this.sensorId = sensorId;
	    this.type = type;
	}


    public String getSensorId()
    {
        return sensorId;
    }


    public Type getType()
    {
        return type;
    }
}
