package org.sensorhub.api.sensor;

import org.sensorhub.api.common.SensorHubException;


/**
 * <p><b>Title:</b>
 * SensorException
 * </p>
 *
 * <p><b>Description:</b><br/>
 * Exceptions generated by the sensor API
 * </p>
 *
 * <p>Copyright (c) 2013</p>
 * @author Alexandre Robin <alex.robin@sensiasoftware.com>
 * @date Sep 5, 2013
 */
public class SensorException extends SensorHubException
{
    private static final long serialVersionUID = -8477183882408329676L;

    
    public SensorException(String message)
    {
        super(message);
    }
    
    
    public SensorException(String message, Throwable cause)
    {
        super(message, cause);
    }
    
    
    public SensorException(String message, int code, Throwable cause)
    {
        super(message, code, cause);
    }    
}
